# Generated by Django 3.0.6 on 2020-05-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JuegosSerios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('autores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuegosSerios.Autores')),
            ],
        ),
    ]
