# Generated by Django 3.0.6 on 2020-05-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JuegosSerios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegosserios',
            name='autores',
        ),
        migrations.AddField(
            model_name='autores',
            name='juego_serio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JuegosSerios.JuegosSerios'),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='complejidad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='dificultad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='documentacion',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='idioma',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Ingles'), ('FR', 'Frances'), ('PO', 'Portugues'), ('OT', 'Otro')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='licencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='manuales',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='pre_requisitos',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='tipo_actividad',
            field=models.CharField(choices=[('Juego Serio', 'Juego Serio'), ('Juego de Simulacion', 'Juego de Simulación')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='tipo_juego',
            field=models.CharField(choices=[('Cooperativo', 'Cooperativo'), ('Competitivo', 'Competitivo'), ('Cooperativo/Competitivo', 'Cooperativo/Competitivo')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='juegosserios',
            name='video',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='autores',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Principios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principio_1', models.TextField(blank=True, verbose_name='empezar de donde estamos')),
                ('principio_2', models.TextField(blank=True, verbose_name='acordar perseguir un cambio evolutivo incremental')),
                ('principio_3', models.TextField(blank=True, verbose_name='respetar el proceso actual, roles, responsabilidades y títulos')),
                ('principio_4', models.TextField(blank=True, verbose_name='fomentar actos de liderazgo en todos los niveles')),
                ('juego_serio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JuegosSerios.JuegosSerios')),
            ],
        ),
        migrations.CreateModel(
            name='Practicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practica_1', models.TextField(blank=True, verbose_name='visualizar el flujo de trabajo')),
                ('practica_2', models.TextField(blank=True, verbose_name='limitar el trabajo en progreso (WIP)')),
                ('practica_3', models.TextField(blank=True, verbose_name='gestionar el flujo')),
                ('practica_4', models.TextField(blank=True, verbose_name='hacer explícitas las políticas del proceso')),
                ('practica_5', models.TextField(blank=True, verbose_name='implementar ciclos de retroalimentación')),
                ('practica_6', models.TextField(blank=True, verbose_name='mejorar colaborativamente')),
                ('juego_serio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JuegosSerios.JuegosSerios')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_1', models.FloatField(choices=[(0, 'No lo cubre'), (0.5, 'Parcialmente lo cubre'), (1, 'Totalmente lo cubre')], default=0, verbose_name='entender los conceptos básicos de Kanban')),
                ('objetivo_2', models.FloatField(choices=[(0, 'No lo cubre'), (0.5, 'Parcialmente lo cubre'), (1, 'Totalmente lo cubre')], default=0, verbose_name='entender como funciona un sistema Kanban')),
                ('objetivo_3', models.FloatField(choices=[(0, 'No lo cubre'), (0.5, 'Parcialmente lo cubre'), (1, 'Totalmente lo cubre')], default=0, verbose_name='aprender los 3 principios de Change Management')),
                ('objetivo_4', models.FloatField(choices=[(0, 'No lo cubre'), (0.5, 'Parcialmente lo cubre'), (1, 'Totalmente lo cubre')], default=0, verbose_name='aprender los principios y practicas fundamentales de Kanban')),
                ('objetivo_5', models.FloatField(choices=[(0, 'No lo cubre'), (0.5, 'Parcialmente lo cubre'), (1, 'Totalmente lo cubre')], default=0, verbose_name='experimentar los beneficios de limitar el trabajo en proceso para mejorar el flujo de trabajo')),
                ('objetivo_6', models.FloatField(choices=[(0, 'No lo cubre'), (0.5, 'Parcialmente lo cubre'), (1, 'Totalmente lo cubre')], default=0, verbose_name='entender como implementar reuniones Kanban en torno al trabajo')),
                ('objetivo_7', models.FloatField(choices=[(0, 'No lo cubre'), (0.5, 'Parcialmente lo cubre'), (1, 'Totalmente lo cubre')], default=0, verbose_name='entender las métricas principales de Kanban')),
                ('juego_serio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JuegosSerios.JuegosSerios')),
            ],
        ),
        migrations.CreateModel(
            name='Metricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrica_1', models.TextField(blank=True, verbose_name='throughput')),
                ('metrica_2', models.TextField(blank=True, verbose_name='tiempo de entrega')),
                ('metrica_3', models.TextField(blank=True, verbose_name='trabajo en progreso (WIP)')),
                ('juego_serio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JuegosSerios.JuegosSerios')),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(blank=True)),
                ('max', models.IntegerField(blank=True)),
                ('juego_serio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JuegosSerios.JuegosSerios')),
            ],
        ),
    ]
