# Generated by Django 3.0.6 on 2020-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuegosSerios', '0002_auto_20200518_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='nombre_completo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='complejidad',
            field=models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='dificultad',
            field=models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='documentacion',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='idioma',
            field=models.CharField(blank=True, choices=[('ES', 'Español'), ('EN', 'Ingles'), ('FR', 'Frances'), ('PO', 'Portugues'), ('OT', 'Otro')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='licencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='manuales',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='pre_requisitos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='tipo_actividad',
            field=models.CharField(blank=True, choices=[('Juego Serio', 'Juego Serio'), ('Juego de Simulacion', 'Juego de Simulación')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='tipo_juego',
            field=models.CharField(blank=True, choices=[('Cooperativo', 'Cooperativo'), ('Competitivo', 'Competitivo'), ('Cooperativo/Competitivo', 'Cooperativo/Competitivo')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='juegosserios',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
