# Generated by Django 3.0.6 on 2020-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuegosSerios', '0003_auto_20200518_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='min',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
