# Generated by Django 3.0.6 on 2020-06-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuegosSerios', '0005_auto_20200525_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegosserios',
            name='duracion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
