# Generated by Django 3.0.6 on 2020-06-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuegosSerios', '0006_auto_20200601_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugerencia', models.TextField()),
                ('experiencia', models.CharField(choices=[('Sin experiencia en Kanban', 'Sin experiencia en Kanban'), ('Poca experiencia en Kanban', 'Poca experiencia en Kanban')], max_length=30)),
                ('perfil', models.CharField(choices=[('Emprendedores', 'Emprendedores'), ('Miembros de empresas u organizaciones', 'Miembros de empresas u organizaciones'), ('Profesionistas de dominios especificos', 'Profesionistas de dominios especificos'), ('Maestros', 'Maestros'), ('Estudiantes', 'Estudiantes')], max_length=40)),
                ('importancia', models.CharField(choices=[(0, 'No aplica'), (1, 'No tan importante'), (2, 'Importante'), (3, 'Muy importante')], max_length=20)),
                ('categoria', models.CharField(choices=[('Objetivos de aprendizaje', 'Objetivos de aprendizaje'), ('Juegos serios', 'Juegos serios'), ('Conceptos básicos', 'Conceptos básicos'), ('Otras sugerencias complementarias', 'Otras sugerencias complementarias')], max_length=40)),
            ],
        ),
    ]
